// for examples
const ADD_ARTICLE = 'ADD_ARTICLE';
const DATA_FETCHED = 'DATA_FETCHED';

// for study guide
const GET_CATEGORIES_BY_USER = 'GET_CATEGORIES_BY_USER';

const ADD_CATEGORY = 'ADD_CATEGORY';

const ADD_TOPIC = 'ADD_TOPIC';

const ADD_NOTE = 'ADD_NOTE';


// authentication
const USER_LOADING = 'USER_LOADING';
const USER_LOADED = 'USER_LOADED';
const AUTH_ERROR = 'AUTH_ERROR';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


// general utility
const LOADING = 'LOADING';
const SUCCESS = 'SUCCESS';
const FAILURE = 'FAILURE';


export {
    ADD_ARTICLE,
    DATA_FETCHED,
    GET_CATEGORIES_BY_USER,
    ADD_CATEGORY,
    ADD_TOPIC,
    ADD_NOTE,
    LOADING,
    SUCCESS,
    FAILURE,
    USER_LOADING,
    USER_LOADED,
    AUTH_ERROR,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    LOGOUT_SUCCESS,
};
